name: MiningWorld
version: 0.1.5
author: SunsetInteractive
main: com.sunsetinteractive.miningworld.MiningWorld
depend: [WorldGuard, Vault]
loadafter: [WorldGuard]
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
loadbefore: [Multiverse-Core]
commands:
    miningworld:
        aliases: [mw, mine, mining, mineworld]
    miningworldconfig:
        aliases: [mwc, mwconfig, mineconfig, mineworldconfig, minesettings]
    miningworldreload:
        aliases: [mwr, minereload, mineworldreload, mwreload]
    miningworldversion:
        aliases: [mwv, mineversion, mineworldversion, mwversion]
    miningworldstats:
        aliases: [mws, minestats, miningstats, mineworldstats, mwstats]
    miningworldupgrades:
        aliases: [mwu, mwupgrades, mineupgrades, miningupgrades, mineworldupgrades]